#page title
page_title                                : Petty Cash                                # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1545263477                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Petty Cash                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Simple Budgeting

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Tayson
your_link                                 : https://tayson.dev
your_city                                 : Toronto
email_address                             : info@pettycash.app
facebook_username                         :
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Zero-Based Budget
    description                           : Assign a job to every dollar and create a monthly budget in 5 minutes.
    fontawesome_icon_name                 : dollar-sign

  - title                                 : Share Budget with Others
    description                           : Invite others to view and enter transactions.
    fontawesome_icon_name                 : user-friends

  - title                                 : iCloud Sync
    description                           : Your data is stored safely on iCloud.
    fontawesome_icon_name                 : cloud

  - title                                 : Expense Chart
    description                           : Visualize your spending and see where your money is going.
    fontawesome_icon_name                 : chart-pie

  - title                                 : CSV Export
    description                           : Export your transactions to Excel, Google Sheets, and Numbers.
    fontawesome_icon_name                 : file-csv

  - title                                 : Face ID Lock
    description                           : Hide sensitive data and require authentication to unlock.
    fontawesome_icon_name                 : lock

  - title                                 : # Smart App Banner
    description                           : # Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : # arrow-alt-circle-down

  - title                                 : # Social Links
    description                           : # Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # link

  - title                                 : # FontAwesome Support
    description                           : # Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#f0f0f5"
topbar_transparency                       : 1.0
topbar_title_color                        : "#000000"

cover_image                               :                                           # Replace with alternative image path or image URL.
cover_overlay_color                       : "#f0f0f5"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#000000"

app_title_color                           : "#000000"
app_price_color                           : "#838388"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#838388"

feature_icons_foreground_color            : "#838388"
feature_icons_background_color            : "#f0f0f5"

social_icons_foreground_color             : "#838388"
social_icons_background_color             : "#f0f0f5"

footer_text_color                         : "#838388"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
